
import json
import os
from datetime import datetime

# CONFIGURATION
SKILL_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHRONICLE_PATH = os.path.join(SKILL_ROOT, "chronicle.json")
DASHBOARD_OUTPUT = os.path.join(SKILL_ROOT, "typhon-dashboard.html")

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Typhon Dashboard | Performance Intelligence</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&display=swap" rel="stylesheet">
    <style>
        :root {{
            --bg: #020617;
            --card-bg: #0f172a;
            --text: #f8fafc;
            --cyan: #22d3ee;
            --emerald: #34d399;
            --rose: #fb7185;
            --slate: #94a3b8;
        }}
        body {{
            background-color: var(--bg);
            color: var(--text);
            font-family: 'JetBrains Mono', monospace;
            margin: 0;
            padding: 40px 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }}
        .container {{ max-width: 1100px; width: 100%; }}
        header {{ text-align: center; margin-bottom: 40px; }}
        header h1 {{ font-size: 2.5rem; margin: 0; color: var(--cyan); }}
        header p {{ color: var(--slate); margin-top: 10px; }}
        
        .stats-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 40px;
        }}
        .stat-card {{
            background: var(--card-bg);
            padding: 20px;
            border-radius: 12px;
            border: 1px solid #1e293b;
            text-align: center;
        }}
        .stat-card .label {{ font-size: 0.8rem; color: var(--slate); text-transform: uppercase; }}
        .stat-card .value {{ font-size: 1.5rem; font-weight: bold; margin-top: 8px; color: var(--emerald); }}

        .chart-container {{
            background: var(--card-bg);
            padding: 25px;
            border-radius: 12px;
            border: 1px solid #1e293b;
            margin-bottom: 30px;
            height: 400px;
        }}
        h2 {{ font-size: 1.2rem; color: var(--cyan); margin-bottom: 20px; }}
        
        footer {{ margin-top: 40px; color: var(--slate); font-size: 0.8rem; }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>TYPHON DASHBOARD</h1>
            <p>Hardware Intelligence & Performance Benchmarking</p>
        </header>

        <div class="stats-grid">
            <div class="stat-card">
                <div class="label">Total Tests</div>
                <div class="value" id="stat-tests">{total_tests}</div>
            </div>
            <div class="stat-card">
                <div class="label">Avg. TPS (Global)</div>
                <div class="value" id="stat-tps">{avg_tps_global}</div>
            </div>
            <div class="stat-card">
                <div class="label">Max VRAM (MB)</div>
                <div class="value" id="stat-vram">{max_vram_global}</div>
            </div>
            <div class="stat-card">
                <div class="label">Last Run</div>
                <div class="value" id="stat-last" style="font-size: 1rem;">{last_run_date}</div>
            </div>
        </div>

        <div class="chart-container">
            <h2>Tokens Per Second vs. Context Size</h2>
            <canvas id="tpsChart"></canvas>
        </div>

        <div class="chart-container">
            <h2>VRAM Usage vs. Context Size</h2>
            <canvas id="vramChart"></canvas>
        </div>

        <footer>
            Generated by Typhon-Stress-Test | Data Source: {chronicle_path}
        </footer>
    </div>

    <script>
        const data = {json_data};

        // Chart Configurations
        const ctxTps = document.getElementById('tpsChart').getContext('2d');
        const ctxVram = document.getElementById('vramChart').getContext('2d');

        // Data Preparation
        // We'll plot the most recent test's curve
        const latestRun = data[0];
        const labels = latestRun.results.map(r => r.context_size);
        const tpsData = latestRun.results.map(r => r.tps);
        const vramData = latestRun.results.map(r => r.vram_used_mb);

        new Chart(ctxTps, {{
            type: 'line',
            data: {{
                labels: labels,
                datasets: [{{
                    label: 'Tokens / Second (TPS)',
                    data: tpsData,
                    borderColor: '#22d3ee',
                    backgroundColor: 'rgba(34, 211, 238, 0.1)',
                    borderWidth: 3,
                    tension: 0.4,
                    fill: true
                }}]
            }},
            options: {{
                responsive: true,
                maintainAspectRatio: false,
                scales: {{
                    x: {{ title: {{ display: true, text: 'Context Size (Tokens)', color: '#94a3b8' }}, ticks: {{ color: '#94a3b8' }} }},
                    y: {{ title: {{ display: true, text: 'Tokens/Sec', color: '#94a3b8' }}, ticks: {{ color: '#94a3b8' }} }}
                }},
                plugins: {{
                    legend: {{ labels: {{ color: '#f8fafc' }} }}
                }}
            }}
        }});

        new Chart(ctxVram, {{
            type: 'line',
            data: {{
                labels: labels,
                datasets: [{{
                    label: 'VRAM Used (MB)',
                    data: vramData,
                    borderColor: '#fb7185',
                    backgroundColor: 'rgba(251, 113, 133, 0.1)',
                    borderWidth: 3,
                    tension: 0.4,
                    fill: true
                }}]
            }},
            options: {{
                responsive: true,
                maintainAspectRatio: false,
                scales: {{
                    x: {{ title: {{ display: true, text: 'Context Size (Tokens)', color: '#94a3b8' }}, ticks: {{ color: '#94a3b8' }} }},
                    y: {{ title: {{ display: true, text: 'VRAM (MB)', color: '#94a3b8' }}, ticks: {{ color: '#94a3b8' }} }}
                }},
                plugins: {{
                    legend: {{ labels: {{ color: '#f8fafc' }} }}
                }}
            }}
        }});
    </script>
</body>
</html>
"""

def generate_dashboard():
    if not os.path.exists(CHRONICLE_PATH):
        print("❌ Error: No chronicle found. Run 'typhon sync' first.")
        return

    with open(CHRONICLE_PATH, 'r') as f:
        chronicle = json.load(f)

    if not chronicle:
        print("⚠️ Chronicle is empty.")
        return

    # Metrics for summary cards
    total_tests = len(chronicle)
    avg_tps_global = sum(e['metrics']['avg_tps'] for e in chronicle) / total_tests
    max_vram_global = max(e['metrics'].get('max_vram_mb', 0) for e in chronicle)
    last_run_date = chronicle[0]['timestamp']

    # Prepare HTML
    html_content = HTML_TEMPLATE.format(
        total_tests=total_tests,
        avg_tps_global=f"{avg_tps_global:.2f}",
        max_vram_global=f"{max_vram_global:,}",
        last_run_date=last_run_date,
        json_data=json.dumps(chronicle),
        chronicle_path=CHRONICLE_PATH
    )

    with open(DASHBOARD_OUTPUT, 'w') as f:
        f.write(html_content)

    print(f"✅ Dashboard generated successfully!")
    print(f"📍 Path: {DASHBOARD_OUTPUT}")
    print(f"🚀 Open it in your browser to see the intelligence.")

if __name__ == "__main__":
    generate_dashboard()
